name: BS-Teams
main: com.github.bkm016.bsteams.BSTeamsPlugin
version: {$VERSION}

authors: [Bkm016, Saukiya]

softdepend: [PlaceholderAPI]

commands:
  bsteams:
    aliases: [teams,bst]
    permission: bsteams.use