name: BS-Teams
main: com.github.bkm016.bsteams.BSTeamsPlugin
version: 1.1.0

authors:
- Bkm016
- Saukiya

softdepend:
- PlaceholderAPI

commands:
  bsteams:
    aliases: [teams,bst,bt]
    permission: bsteams.use